### ISSUE TITLE
this.params.dataSource.fetch is not a function

### ISSUE THREAD

**Issue by Lutherwaves** [ABD-dev/ngx-twitter-timeline#17]
I had this component loaded into my Ionic 4 app earlier this year. 
After some Angular and Ionic Cli updates earlier the other month I get the following error and nothing displayed on the page: 

``
zone.js:682 Unhandled Promise rejection: this.params.dataSource.fetch is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.params.dataSource.fetch is not a function
    at e.<anonymous> (timeline.4c6ab682148a0366f9efb1647a3f4799.js:1)
    at e.hydrate (widgets.js:8)
    at c.hydrate (widgets.js:8)
    at widgets.js:8
    at Array.forEach (<anonymous>)
    at widgets.js:8
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601) TypeError: this.params.dataSource.fetch is not a function
    at e.<anonymous> (https://platform.twitter.com/js/timeline.4c6ab682148a0366f9efb1647a3f4799.js:1:14330)
    at e.hydrate (https://platform.twitter.com/widgets.js:8:28972)
    at c.hydrate (https://platform.twitter.com/widgets.js:8:23168)
    at https://platform.twitter.com/widgets.js:8:8257
    at Array.forEach (<anonymous>)
    at https://platform.twitter.com/widgets.js:8:8228
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8100/polyfills.js:2749:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:8100/polyfills.js:2508:43)
    at http://localhost:8100/polyfills.js:3247:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:2781:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:8100/polyfills.js:2553:47)
    at drainMicroTaskQueue (http://localhost:8100/polyfills.js:2959:35)
``

as I am currently writing my bachelor's degree on this, I would be really happy if any of you have a solution for the problem. I've googled a lot and couldn't find an event remotely similar error anywhere.

Here is my ionic info output for reference as well:
`` 
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 13 other plugins)

System:

   NodeJS : v10.15.0 (C:\Development\nodejs\node.exe)
   npm    : 6.8.0
   OS     : Windows 10
``

**Comment by sostoli** [comment]
Same issue here!

**Comment by sostoli** [comment]
@Lutherwaves have you found a solution?

**Comment by Lutherwaves** [comment]
> @Lutherwaves have you found a solution?

Sadly, have not found a way to make it work using this plugin. I might just try to embed the timeline myself.

**Comment by narendralussspacetech** [comment]
I was suffered the same issue. I checked and found that the issue was with twitter URL having space which might be wrong as per twitter URL policy.  Hope this helps others as the solution and ticket closer. Thanks :)
